interface Team {
  arena: string,
  city: string,
  fullName: string,
  teamId: string,
  tricode: string
}

const teamList: Team[] = [
  {
    arena: 'State Farm Arena',
    city: 'Atlanta',
    fullName: 'Atlanta Hawks',
    teamId: '1610612737',
    tricode: 'ATL',
  },
  {
    arena: 'TD Garden',
    city: 'Boston',
    fullName: 'Boston Celtics',
    teamId: '1610612738',
    tricode: 'BOS',
  },
  {
    arena: 'Barclays Center',
    city: 'Brooklyn',
    fullName: 'Brooklyn Nets',
    teamId: '1610612751',
    tricode: 'BKN',
  },
  {
    arena: 'Spectrum Center',
    city: 'Charlotte',
    fullName: 'Charlotte Hornets',
    teamId: '1610612766',
    tricode: 'CHA',
  },
  {
    arena: 'United Center',
    city: 'Chicago',
    fullName: 'Chicago Bulls',
    tricode: 'CHI',
    teamId: '1610612741',
  },
  {
    arena: 'Rocket Mortgage FieldHouse',
    city: 'Cleveland',
    fullName: 'Cleveland Cavaliers',
    teamId: '1610612739',
    tricode: 'CLE',
  },
  {
    arena: 'American Airlines Center',
    city: 'Dallas',
    fullName: 'Dallas Mavericks',
    teamId: '1610612742',
    tricode: 'DAL',
  },
  {
    arena: 'Ball Arena',
    city: 'Denver',
    fullName: 'Denver Nuggets',
    tricode: 'DEN',
    teamId: '1610612743',
  },
  {
    arena: 'Little Caesars Arena',
    city: 'Detroit',
    fullName: 'Detroit Pistons',
    tricode: 'DET',
    teamId: '1610612765',
  },
  {
    arena: 'Chase Center',
    city: 'Golden State',
    fullName: 'Golden State Warriors',
    teamId: '1610612744',
    tricode: 'GSW',
  },
  {
    arena: 'Toyota Center',
    city: 'Houston',
    fullName: 'Houston Rockets',
    teamId: '1610612745',
    tricode: 'HOU',
  },
  {
    arena: 'Bankers Life Fieldhouse',
    city: 'Indiana',
    fullName: 'Indiana Pacers',
    teamId: '1610612754',
    tricode: 'IND',
  },
  {
    arena: 'Crypto.com Arena',
    city: 'LA',
    fullName: 'LA Clippers',
    teamId: '1610612746',
    tricode: 'LAC',
  },
  {
    arena: 'Crypto.com Arena',
    city: 'Los Angeles',
    fullName: 'Los Angeles Lakers',
    teamId: '1610612747',
    tricode: 'LAL',
  },
  {
    arena: 'FedExForum',
    city: 'Memphis',
    fullName: 'Memphis Grizzlies',
    teamId: '1610612763',
    tricode: 'MEM',
  },
  {
    arena: 'FTX Arena',
    city: 'Miami',
    fullName: 'Miami Heat',
    teamId: '1610612748',
    tricode: 'MIA',
  },
  {
    arena: 'Fiserv Forum',
    city: 'Milwaukee',
    fullName: 'Milwaukee Bucks',
    teamId: '1610612749',
    tricode: 'MIL',
  },
  {
    arena: 'Target Center',
    city: 'Minnesota',
    fullName: 'Minnesota Timberwolves',
    teamId: '1610612750',
    tricode: 'MIN',
  },
  {
    arena: 'Smoothie King Center',
    city: 'New Orleans',
    fullName: 'New Orleans Pelicans',
    teamId: '1610612740',
    tricode: 'NOP',
  },
  {
    arena: 'Madison Square Garden',
    city: 'New York',
    fullName: 'New York Knicks',
    teamId: '1610612752',
    tricode: 'NYK',
  },
  {
    arena: 'Paycom Center',
    city: 'Oklahoma City',
    fullName: 'Oklahoma City Thunder',
    teamId: '1610612760',
    tricode: 'OKC',
  },
  {
    arena: 'Amway Center',
    city: 'Orlando',
    fullName: 'Orlando Magic',
    teamId: '1610612753',
    tricode: 'ORL',
  },
  {
    arena: 'Wells Fargo Center',
    city: 'Philadelphia',
    fullName: 'Philadelphia 76ers',
    teamId: '1610612755',
    tricode: 'PHI',
  },
  {
    arena: 'Footprint Center',
    city: 'Phoenix',
    fullName: 'Phoenix Suns',
    teamId: '1610612756',
    tricode: 'PHX',
  },
  {
    arena: 'Moda Center',
    fullName: 'Portland Trail Blazers',
    city: 'Portland',
    teamId: '1610612757',
    tricode: 'POR',
  },
  {
    arena: 'Golden 1 Center',
    city: 'Sacramento',
    fullName: 'Sacramento Kings',
    teamId: '1610612758',
    tricode: 'SAC',
  },
  {
    arena: 'AT&T Center',
    fullName: 'San Antonio Spurs',
    city: 'San Antonio',
    teamId: '1610612759',
    tricode: 'SAS',
  },
  {
    arena: 'Scotiabank Arena',
    city: 'Toronto',
    fullName: 'Toronto Raptors',
    teamId: '1610612761',
    tricode: 'TOR',
  },
  {
    arena: 'Vivint Arena',
    city: 'Utah',
    fullName: 'Utah Jazz',
    teamId: '1610612762',
    tricode: 'UTA',
  },
  {
    arena: 'Capital One Arena',
    city: 'Washington',
    fullName: 'Washington Wizards',
    teamId: '1610612764',
    tricode: 'WAS',
  },
];

export default teamList;
